<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="8" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="109" started-at="2019-09-27T04:58:22Z" finished-at="2019-09-27T04:58:22Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="109" started-at="2019-09-27T04:58:22Z" finished-at="2019-09-27T04:58:22Z">
      <class name="learnTestNG.TestNGDemo1">
        <test-method status="PASS" signature="m()[pri:0, instance:learnTestNG.TestNGDemo1@5e5792a0]" name="m" duration-ms="15" started-at="2019-09-27T04:58:22Z" finished-at="2019-09-27T04:58:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m -->
        <test-method status="PASS" signature="m1()[pri:1, instance:learnTestNG.TestNGDemo1@5e5792a0]" name="m1" duration-ms="2" started-at="2019-09-27T04:58:22Z" finished-at="2019-09-27T04:58:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m1 -->
        <test-method status="PASS" signature="m2()[pri:2, instance:learnTestNG.TestNGDemo1@5e5792a0]" name="m2" duration-ms="1" started-at="2019-09-27T04:58:22Z" finished-at="2019-09-27T04:58:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m2 -->
        <test-method status="FAIL" signature="m3()[pri:3, instance:learnTestNG.TestNGDemo1@5e5792a0]" name="m3" duration-ms="3" started-at="2019-09-27T04:58:22Z" finished-at="2019-09-27T04:58:22Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Method m3() was purposelyfailed to understand depends behavior in TestNG]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Method m3() was purposelyfailed to understand depends behavior in TestNG
at org.testng.Assert.fail(Assert.java:96)
at learnTestNG.TestNGDemo1.m3(TestNGDemo1.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m3 -->
        <test-method status="PASS" signature="m4()[pri:4, instance:learnTestNG.TestNGDemo1@5e5792a0]" name="m4" duration-ms="2" started-at="2019-09-27T04:58:22Z" finished-at="2019-09-27T04:58:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m4 -->
        <test-method status="PASS" signature="m4()[pri:4, instance:learnTestNG.TestNGDemo1@5e5792a0]" name="m4" duration-ms="2" started-at="2019-09-27T04:58:22Z" finished-at="2019-09-27T04:58:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m4 -->
        <test-method status="PASS" signature="m4()[pri:4, instance:learnTestNG.TestNGDemo1@5e5792a0]" name="m4" duration-ms="1" started-at="2019-09-27T04:58:22Z" finished-at="2019-09-27T04:58:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m4 -->
        <test-method status="SKIP" signature="m5()[pri:5, instance:learnTestNG.TestNGDemo1@5e5792a0]" name="m5" duration-ms="0" started-at="2019-09-27T04:58:22Z" depends-on-methods="learnTestNG.TestNGDemo1.m3" finished-at="2019-09-27T04:58:22Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestNGDemo1.m5()[pri:5, instance:learnTestNG.TestNGDemo1@5e5792a0] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestNGDemo1.m5()[pri:5, instance:learnTestNG.TestNGDemo1@5e5792a0] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m5 -->
      </class> <!-- learnTestNG.TestNGDemo1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
